# Generated by Django 3.2.3 on 2021-05-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('screen_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('screen_resolution', models.CharField(max_length=50, verbose_name='Разрешение экрана')),
                ('ram', models.PositiveSmallIntegerField(verbose_name='Оперативная память, Гб')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Встроенная память, Гб')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('views', models.IntegerField(default=0)),
                ('sim_amount', models.IntegerField(verbose_name='Количество SIM-карт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.categories', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('screen_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('screen_resolution', models.CharField(max_length=50, verbose_name='Разрешение экрана')),
                ('ram', models.PositiveSmallIntegerField(verbose_name='Оперативная память, Гб')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Встроенная память, Гб')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('views', models.IntegerField(default=0)),
                ('gpu', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процессор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.categories', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
