# Generated by Django 3.2.3 on 2021-05-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.brand', verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.brand', verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
