# Generated by Django 3.2.3 on 2021-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210522_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('Изображение', models.ImageField(blank=True, null=True, upload_to='sliders/%y/%m/%d')),
            ],
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
    ]
