# Generated by Django 3.2.3 on 2021-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210523_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
