# Generated by Django 3.2.3 on 2021-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_newsletterrecipientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipientemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
