# Generated by Django 3.2.3 on 2021-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_newsletterrecipientemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipientemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-19 12:55:49'),
            preserve_default=False,
        ),
    ]
