# Generated by Django 3.2.3 on 2021-05-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_newsletterrecipientemail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='Фото 4'),
        ),
    ]
