# Generated by Django 3.2.3 on 2021-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210525_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Изображение',
        ),
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/%y/%m/%d', verbose_name='Изображение слайдер'),
        ),
    ]
