# Generated by Django 3.2.3 on 2021-05-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210525_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Device',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
