# Generated by Django 3.2.3 on 2021-05-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210525_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu',
            field=models.CharField(max_length=255, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gpu',
            field=models.CharField(max_length=255, verbose_name='GPU'),
        ),
        migrations.AlterField(
            model_name='device',
            name='memory',
            field=models.PositiveSmallIntegerField(verbose_name='Memory, Gb'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram',
            field=models.PositiveSmallIntegerField(verbose_name='RAM, Gb'),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_resolution',
            field=models.CharField(max_length=50, verbose_name='Screen Resolution'),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_size',
            field=models.CharField(max_length=50, verbose_name='Screen size'),
        ),
        migrations.AlterField(
            model_name='device',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='device',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/%y/%m/%d', verbose_name='Slider image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
