# Generated by Django 3.2.3 on 2021-05-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210526_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecipientEmail',
            new_name='SubscriberEmail',
        ),
    ]
